[package]
name = "builder_pattern"
version = "0.1.0"
authors = ["David Meredith <david.meredith@stfc.ac.uk>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
